// ----------------------------------------------------------------------
// -- COURSE SETTINGS:
// ----------------------------------------------------------------------
// -- NOTE: Do not edit this file unless you are a WDS team member.
// -- ABOUT: This file loads all libraries and creates each page.
// -- Authors/Assembler: jmullins@flvs.net
// -- Based on the work/code of Mike Jarrell
// ======================================================================

// ----------------------------------------------------------------------
// -- CDN SETTINGS
// ----------------------------------------------------------------------	
var course_location = "live"; // live, local
var core_folder = 'testcourse'; // From Root - IF SET to Local this is where the core files should be
var CFVersion = '4.0';

// ----------------------------------------------------------------------
// -- INCLUDED FILES
// ----------------------------------------------------------------------
// -- String Array
// -- example: '../global/js/jslibs.js',...
// ----------------------------------------------------------------------
var course_csslibs = [];
var course_jslibs = [];

// ----------------------------------------------------------------------
// -- GENERAL COURSE SETTINGS
// ----------------------------------------------------------------------
var settings = {}; // do not edit
var show = {}; // do not edit
var external = {}; // do not edit

settings['course_folder'] = 'testcourse';
settings['course_title'] = 'CSQA Training';
settings['link_glossary'] = '';
settings['link_notes'] = '';
settings['use_local_language'] = false; // Uses local language file instead of global language file.
settings['show_page_number_by'] = 'lesson'; //module or lesson, this will be the 1 of 4 (number of pages in current lesson, or current module)
settings['developers'] = ['Joseph Willis'];
settings['default_menu'] = true; // This will display the default drop down menu, turn it off if you have a custom one -- if set to false you need to add your menu to global/js/course.js

// Look & Feel
settings['uiSkin'] = 'ui_interactive_skin_template'; //jQueryUI CSS file, located in global/css/ilskin
settings['meSkin'] = ''; //MediaElements CSS file, located in global/css
settings['course_font'] = ''; //external fonts Link
settings['flvs_logo_type'] = 'color'; // color, white, black
settings['home_show_title'] = true;
settings['home_popup_top_position'] = 70;
settings['home_popup_animation'] = 'slide'; // options are slide or fade
//**Android fixed layout items converts to absolute positioning (position: fixed css items)
settings['layout_fixed_css'] = ''; //defaults: #headbar, #side_nav, #menu, #menua, #nav_menu

// Advanced Settings
settings['local_root'] = 'global'; //folder name, global is default
settings['course_home'] = 'index.htm';
settings['use_analytics'] = false;
settings['ua_account'] = ''; // your dedicated GoogleUA account number
settings['sitemap_dir'] = 'global/xml/sitemap.xml';


// Template Definitions are class names of elements that need to be removed from the template when on 
// small mobile devices	and external pages.	(String Array)			
var template_defs = {/*header,footer, */};

// Show / Hide Objects (true/false)									
show['notes_link'] = true;
show['glossary_link'] = true;
show['bookmarks_link'] = false;
show['text_resize_links'] = false;
show['progress_bar'] = true;
show['developer_credit'] = true;
show['menu'] = true;

// ----------------------------------------------------------------------
// -- CUSTOM MENU ITEMS
// ----------------------------------------------------------------------
// -- Array Object [ Strings ]
// -- [0] = Link Title, [1] = Link, [2] = pop/modal-pop, [3] = class name for styling
// ----------------------------------------------------------------------
var custom_menu_items = [
	//['Resources','../global/copyright.htm','modal-pop','resource_link']
];

// ----------------------------------------------------------------------
// -- RENDER COURSE FOR 3RD PARTY
// ----------------------------------------------------------------------
external['render_for_ca'] = false; // true removes all menu items, turns on course language, removes lesson numbers, uses local language file
external['render_for_gs'] = false; // true uses local language file 
external['show_flvs_copyright'] = true; //true or false to show copyright


// ----------------------------------------------------------------------
// -- DO NOT EDIT BELOW THIS LINE
// ----------------------------------------------------------------------

//---Since this is our first page that loads, use it to hide body---//
//---except for android, some issue with visibility---//
var ua = navigator.userAgent.toLowerCase();
var isAndroid = ua.indexOf("android") > -1; 
if(!isAndroid) {
	document.write('<style>body{visibility: hidden;}</style>');
}else{
	settings['isAndroid'] = true;
}


var cdn_location = "http://107.23.178.245/cdn/"+ CFVersion ;

// FLVS Global Object
var FLVS = {
		settings:settings,
		Sitemap:'',
		ui_options : ''
	}; 

//location adjustment for live to local
//these can change based on your placement of the FW core files
var pathArray = window.location.pathname.split( '/' );
pathArray = pathArray.filter(function(v){return v!==''});
var maxPath = pathArray.length;
var currentPath = pathArray.indexOf(settings.course_folder)+1 //---arrays start at 0
var countTO = maxPath - currentPath;
//console.log(window.location.pathname, maxPath, currentPath, countTO);
 if (currentPath === -1 || currentPath === 0){
	var r = confirm("There seems to be a problem, please contact the help desk. **Error 104");
 }

var rootSet = "";
for ( i=1; i < countTO; i++)
{ 
	rootSet = "../"+rootSet;
}

//----prevent direct folder adresses from messing up the count, ex. /cheatsheet/ vs /cheatsheet/index.htm, but not the homepage----/
if(countTO === 1 && rootSet === "" && typeof isindex === 'undefined'){rootSet = "../";}



//-------- these are to find all js, css files in other core files ---------//
var url_fromGlobal = (course_location == 'local') ? rootSet+core_folder : cdn_location; 
var url_fromHome = (course_location == 'local') ? core_folder : cdn_location; 
var ill_core_plugins = url_fromGlobal+"/scripts/il/plugins/";
//console.log(maxPath,currentPath, countTO);
//console.log("url_fromGlobal:" + url_fromGlobal);


//-------- these are specifically to pull in require.js -------//
//-------- do not edit, unless you are FW team ----------------//
var imported = document.createElement('script');
var att = document.createAttribute("data-main");
if(typeof isindex != 'undefined' && isindex == true){
	imported.src = url_fromHome+'/scripts/require.js';
	att.value = url_fromHome+'/scripts/start.js';
//}else if(){
	
}else{
	imported.src = url_fromGlobal+'/scripts/require.js';
	att.value = url_fromGlobal+'/scripts/start.js';
}
document.head.appendChild(imported).setAttributeNode(att);


//-------- these are used by require, it thinks everything is in the same folder as it, a little different path ---------//
//-------- we need to get the current url and massage it to get into the global------------------------------------------//
var newURL = window.location.protocol + "//" + window.location.host + window.location.pathname;
var n = newURL.indexOf(settings['course_folder']);
var url_forRequire = newURL.substring(0, n)+settings['course_folder']+"/"+settings['local_root']+"/js"; 
var url_forStyle = newURL.substring(0, n)+settings['course_folder']+"/"+settings['local_root']+"/css"; 
